### ISSUE TITLE
Fix background audio

### ISSUE THREAD

**Issue by kazuyabr** [damian-pastorini/reldens#181] opened 2021-12-22 20:16 UTC
Whenever we move, the game's sound resets leaving us annoyed with the audio and trying to turn off the music.
Could you fix the asynchronous audio call to prevent any interaction on the map causing the music to restart?
I'm new to the project and it would take me a long time to understand how this works to the point where I have the way to fix it myself.
Taking advantage, have you thought about using a non-relational database? I'm thinking about using rethinkdb for this project because I've noticed a certain lag in it and I believe that a real-time database like RethinkDB can solve our problem a lot on the server side.
I will contribute to the project where I can =D

**Comment by damian-pastorini** [comment] 2021-12-23 06:21
hi @kazuyabr , I think I have a fix already for the audio in the new beta.19, I will try to cherry pick it but there are a lot of changes related to the audios becuase the new admin coming.
Additionally, with the new admin in the beta.19 I've also included storage drivers and one of those is for MikroORM which will allow us to use non-relational databases.
I'll keep you posted as soon I have news on this.

Thanks for reporting! You should join our Discord channel :) 

Regards,
Damian

**Comment by kazuyabr** [comment] 2021-12-23 13:55
So in reality I already participate in the discord.
But there is an area Brazil lacking there, because I'm Brazilian and I speak Portuguese.
It's easier for me to speak in my own language kkk, but let's go.
Next I want to contribute to the development, but this part of the initial audio bothers me a lot, if I can send a DIFF just to fix this problem, it helps me not to have to change the game.
First I want to create a character creation scene with several sprites to choose from (typical of MMORPG).
Another thing, have you ever used PhaserJS Editor? looks like an excellent tool to speed up Phaser project development.
Take a look, I think you'll like it: https://phaseeditor2d.com/

**Comment by damian-pastorini** [comment] 2021-12-23 14:55
The best options I can offer you is spanish :D I'm from Argentina LOL

If you want a quick fix you can disabled or remove the audio from the database.
It may take me a while until I get back on the road since I've got really bad luck with the last laptop I've got and the SSD died after 2 months of use... so I'm in the middle of the recovery process and setting up everything again.

> First I want to create a character creation scene with several sprites to choose from (typical of MMORPG).
You mean several sprites for a single player? If you get that working and contribute to this project I would love to get that feature.

I've never used Phaser editor, only TiledMap Editor because I needed to get a standard way of generate maps, but after that any animations or whatever game-related stuff users want to create that will be custom game-theme related, so out of the scope of the project.

**Comment by kazuyabr** [comment] 2021-12-23 20:09
Yes, several sprites for a single player, but for that to happen I need to adapt to the project and its creation method. That said it may take a while, but when it's done I'll do a PR for you.

**Comment by damian-pastorini** [comment] 2022-01-14 19:40
hi @kazuyabr I've been trying to reproduce the music issue but so far I wasn't able to do it, so a few questions:
- Does it happen to you on the demo? https://demo.reldens.com/
- Is happening on some specific browser or device?
- Does it happen you do some specifc action in the game or follow up some specific patern?
Any other extra information about will be appreaciated!
Thanks!

**Comment by damian-pastorini** [comment] 2022-03-03 18:59
I'm closing the issue, I couldn't reproduce it and a lot of things changed related to the audios packages.
Now the contents can be modified from the admin and the audios package is one of the packages that already have the hot-plug feature fully working.

**Closed by damian-pastorini** 2022-03-03 18:59 UTC
